export const constants = {
	HEADER_TEXT: "Development Books",
	BOOKLIST_HEADING: "Available Books",
	SHOW_CART_BTN_LABEL: "Show Cart",
	CLOSE_CART_BTN_LABEL: "Close Cart",
	MISSING_URL_MESSAGE: "Request failed.., URL not found!",
	API_URL: "http://localhost:3001/books",
	NO_RESULTS_MESSAGE: "Book shelf is Empty.., Comeback later",
	ZERO: 0,
	CART_QTY_ONE: 1,
	ADD_TO_CART_BTN_TEXT: "Add to Cart",

	TEST_ID_SHOW_CART_BTN: "showCartBtn",
	TEST_ID_BAG_ICON: "bagIcon",
	TEST_ID_CART_OVERLAY: "cartOverlay",
	TEST_ID_CART: "cart",
	TEST_ID_CLOSE_CART_BTN: "closeCartBtn",
	TEST_ID_XMARK_ICON: "xMarkIcon",
	TEST_ID_BOOK_IMAGE: "bookImage",
	TEST_ID_BOOK_TITLE: "bookTitle",
	TEST_ID_BOOK_PRICE: "bookPrice",
	TEST_ID_CART_QTY_BANNER: "cartQuantityBanner",
};
