export const constants = {
	HEADER_TEXT: "Development Books",
	BOOKLIST_HEADING: "Available Books",
	SHOW_CART_BTN_LABEL: "Show Cart",
	CLOSE_CART_BTN_LABEL: "Close Cart",
	MISSING_URL_MESSAGE: "Request failed.., URL not found!",
	API_URL: "http://localhost:3001/books",
	NO_RESULTS_MESSAGE: "Book shelf is Empty.., Comeback later",
	ZERO: 0,
	CART_QTY_ONE: 1,
	ADD_TO_CART_BTN_TEXT: "Add to Cart",
	CHECK_MARK: "\u2713",
	EMPTY_CART_IMAGE: "./src/assets/add-to-cart.png",
	EMPTY_CART_IMAGE_ALT_TEXT: "Empty Cart Image",
	EMPTY_CART_MESSAGE: "Your cart is Empty...",
	CART_SUMMARY_HEADING_TEXT: "Cart Summary",
	DECIMAL_POINTS: 2,
	HUNDRED: 100,
	PRICE_TYPE_TOTAL_PRICE: "Total Price",
	PRICE_TYPE_DISCOUNT_PRICE: "Discount Price",
	PRICE_TYPE_FINAL_PRICE: "Final Price",

	TEST_ID_SHOW_CART_BTN: "showCartBtn",
	TEST_ID_BAG_ICON: "bagIcon",
	TEST_ID_CART_OVERLAY: "cartOverlay",
	TEST_ID_CART: "cart",
	TEST_ID_CLOSE_CART_BTN: "closeCartBtn",
	TEST_ID_XMARK_ICON: "xMarkIcon",
	TEST_ID_BOOK_IMAGE: "bookImage",
	TEST_ID_BOOK_TITLE: "bookTitle",
	TEST_ID_BOOK_PRICE: "bookPrice",
	TEST_ID_CART_QTY_BANNER: "cartQuantityBanner",
	TEST_ID_EMPTY_CART: "emptyCart",
	TEST_ID_EMPTY_CART_IMAGE: "emptyCartImage",
	TEST_ID_CART_ITEM_TITLE: "cartItemTitle",
	TEST_ID_CART_ITEM_QTY: "cartItemQuantity",
	TEST_ID_CART_ITEM_PRICE: "cartItemPrice",

	DISCOUNT_RULE: { 1: 0, 2: 5 },
};
