export const testConstants = {
	HEADER_TEXT: "Development Books",
	BOOKLIST_HEADING: "Available Books",
	MISSING_URL_MESSAGE: "Request failed.., URL not found!",
	NETWORK_ERROR: "Network Error",
	NO_RESULTS_MESSAGE: "Book shelf is Empty.., Comeback later",
	EMPTY_ARRAY: [],
	ONE: "1",
	CHECK_MARK: "\u2713",
	EMPTY_CART_IMAGE: "./src/assets/add-to-cart.png",
	EMPTY_CART_MESSAGE: "Your cart is Empty...",
	BOOK_ONE_TITLE: "Clean Code",
	BOOK_ONE_QTY: "1",
	BOOK_ONE_PRICE: "₹50.00",

	TEST_ID_SHOW_CART_BTN: "showCartBtn",
	TEST_ID_BAG_ICON: "bagIcon",
	TEST_ID_CART_OVERLAY: "cartOverlay",
	TEST_ID_CART: "cart",
	TEST_ID_CLOSE_CART_BTN: "closeCartBtn",
	TEST_ID_XMARK_ICON: "xMarkIcon",
	TEST_ID_BOOK_IMAGE: "bookImage",
	TEST_ID_BOOK_TITLE: "bookTitle",
	TEST_ID_BOOK_PRICE: "bookPrice",
	TEST_ID_CART_QTY_BANNER: "cartQuantityBanner",
	TEST_ID_EMPTY_CART: "emptyCart",
	TEST_ID_EMPTY_CART_IMAGE: "emptyCartImage",
	TEST_ID_CART_ITEM_TITLE: "cartItemTitle",
	TEST_ID_CART_ITEM_QTY: "cartItemQuantity",
	TEST_ID_CART_ITEM_PRICE: "cartItemPrice",
	TEST_ID_BOOK: "book",
	TEST_ID_INCREASE_BOOK_QTY_BTN: "increaseBookQuantity",
	TEST_ID_PLUS_ICON: "plusIcon",
	TEST_ID_DECREASE_BOOK_QTY_BTN: "decreaseBookQuantity",
	TEST_ID_MINUS_ICON: "minusIcon",
	TEST_ID_REMOVE_BOOK_FROM_CART_BTN: "removeBookFromCart",
	TEST_ID_TRASH_CAN_ICON: "trashCanIcon",
	TEST_ID_CLEAR_CART_BTN: "clearCart",

	TEST_ID_ADD_TO_CART_BTN_BOOK1: "TEST_ID_Clean Code",
	TEST_ID_ADD_TO_CART_BTN_BOOK2: "TEST_ID_The Clean Coder",
	TEST_ID_ADD_TO_CART_BTN_BOOK3: "TEST_ID_Clean Architecture",
	TEST_ID_ADD_TO_CART_BTN_BOOK4: "TEST_ID_Test Driven Development by Example",
	TEST_ID_ADD_TO_CART_BTN_BOOK5: "TEST_ID_Working Effectively With Legacy Code",

	TEST_ID_TOTAL_PRICE_LABEL: "TEST_ID_PRICE_TYPE_Total Price",
	TEST_ID_DISCOUNT_PRICE_LABEL: "TEST_ID_PRICE_TYPE_Discount Price",
	TEST_ID_FINAL_PRICE_LABEL: "TEST_ID_PRICE_TYPE_Final Price",

	TEST_ID_TOTAL_PRICE_VALUE: "TEST_ID_PRICE_VALUE_Total Price",
	TEST_ID_DISCOUNT_PRICE_VALUE: "TEST_ID_PRICE_VALUE_Discount Price",
	TEST_ID_FINAL_PRICE_VALUE: "TEST_ID_PRICE_VALUE_Final Price",

	TOTAL_PRICE_FOR_ONE_BOOK: "₹50.00",
	DISCOUNT_PRICE_FOR_ONE_BOOK: "₹0.00",
	FINAL_PRICE_FOR_ONE_BOOK: "₹50.00",
	TOTAL_PRICE_FOR_TWO_BOOK: "₹100.00",
	DISCOUNT_PRICE_FOR_TWO_BOOK: "₹5.00",
	FINAL_PRICE_FOR_TWO_BOOK: "₹95.00",
	TOTAL_PRICE_FOR_THREE_BOOK: "₹150.00",
	DISCOUNT_PRICE_FOR_THREE_BOOK: "₹15.00",
	FINAL_PRICE_FOR_THREE_BOOK: "₹135.00",
	TOTAL_PRICE_FOR_FOUR_BOOK: "₹200.00",
	DISCOUNT_PRICE_FOR_FOUR_BOOK: "₹40.00",
	FINAL_PRICE_FOR_FOUR_BOOK: "₹160.00",
	TOTAL_PRICE_FOR_FIVE_BOOK: "₹250.00",
	DISCOUNT_PRICE_FOR_FIVE_BOOK: "₹62.50",
	FINAL_PRICE_FOR_FIVE_BOOK: "₹187.50",

	TOTAL_PRICE_FOR_TWO_COPY_OF_SAME_BOOK: "₹100.00",
	DISCOUNT_PRICE_FOR_TWO_COPY_OF_SAME_BOOK: "₹0.00",
	FINAL_PRICE_FOR_TWO_COPY_OF_SAME_BOOK: "₹100.00",

	TOTAL_PRICE_FOR_TWO_COPY_OF_TWO_BOOK: "₹200.00",
	DISCOUNT_PRICE_FOR_TWO_COPY_OF_TWO_BOOK: "₹10.00",
	FINAL_PRICE_FOR_TWO_COPY_OF_TWO_BOOK: "₹190.00",

	TOTAL_PRICE_FOR_THREE_BOOK_WIH_ONE_COPY: "₹150.00",
	DISCOUNT_PRICE_FOR_THREE_BOOK_WIH_ONE_COPY: "₹5.00",
	FINAL_PRICE_FOR_THREE_BOOK_WIH_ONE_COPY: "₹145.00",

	TOTAL_PRICE_FOR_EDGE_CASE: "₹400.00",
	DISCOUNT_PRICE_FOR_EDGE_CASE: "₹80.00",
	FINAL_PRICE_FOR_EDGE_CASE: "₹320.00",

	BOOK_TITLES: [
		"Clean Code",
		"The Clean Coder",
		"Clean Architecture",
		"Test Driven Development by Example",
		"Working Effectively With Legacy Code",
	],
	FORMATED_BOOK_TITLES: [
		"Clean Code",
		"The Clean Coder",
		"Clean Architecture",
		"Test Driven Development ...",
		"Working Effectively With...",
	],

	BOOK_ONE: 0,
	BOOK_TWO: 1,
	BOOK_THREE: 2,

	BOOKS: [
		{
			id: "11d03f1a-66fa-46b1-a473-6a9e24090fb4",
			imgSrc: "./src/assets/Kata_DevelopmentBooks_CleanCode.png",
			title: "Clean Code",
			price: 50,
		},
		{
			id: "d701c4e5-1def-46d7-a3d7-957355fe05fe",
			imgSrc: "./src/assets/Kata_DevelopmentBooks_CleanCoder.png",
			title: "The Clean Coder",
			price: 50,
		},
		{
			id: "c6e03e68-adb5-4ecd-b1a2-be25079f3324",
			imgSrc: "./src/assets/Kata_DevelopmentBooks_CleanArchitecture.jpeg",
			title: "Clean Architecture",
			price: 50,
		},
		{
			id: "87a91bcc-e37f-4251-afd8-33d060b93167",
			imgSrc: "./src/assets/Kata_DevelopmentBooks_TDD.jpeg",
			title: "Test Driven Development by Example",
			price: 50,
		},
		{
			id: "12eab0be-4a7e-4ba3-a27c-be017c13e6e0",
			imgSrc: "./src/assets/Kata_DevelopmentBooks_Refactoring.jpeg",
			title: "Working Effectively With Legacy Code",
			price: 50,
		},
	],

	DISCOUNT_MESSAGE:
		"Combine different books for exclusive discounts --> 2 books - 5% | 3 books - 10% | 4 books - 20% | 5 books - 25% <--",
};
