export const testConstants = {
	HEADER_TEXT: "Development Books",
	BOOKLIST_HEADING: "Available Books",
	MISSING_URL_MESSAGE: "Request failed.., URL not found!",
	NETWORK_ERROR: "Network Error",
	NO_RESULTS_MESSAGE: "Book shelf is Empty.., Comeback later",
	EMPTY_ARRAY: [],
	ONE: "1",
	CHECK_MARK: "\u2713",
	EMPTY_CART_IMAGE: "./src/assets/add-to-cart.png",
	EMPTY_CART_MESSAGE: "Your cart is Empty...",
	BOOK_ONE_TITLE: "Clean Code",
	BOOK_ONE_QTY: "1",
	BOOK_ONE_PRICE: "₹50.00",

	TEST_ID_SHOW_CART_BTN: "showCartBtn",
	TEST_ID_BAG_ICON: "bagIcon",
	TEST_ID_CART_OVERLAY: "cartOverlay",
	TEST_ID_CART: "cart",
	TEST_ID_CLOSE_CART_BTN: "closeCartBtn",
	TEST_ID_XMARK_ICON: "xMarkIcon",
	TEST_ID_BOOK_IMAGE: "bookImage",
	TEST_ID_BOOK_TITLE: "bookTitle",
	TEST_ID_BOOK_PRICE: "bookPrice",
	TEST_ID_CART_QTY_BANNER: "cartQuantityBanner",
	TEST_ID_EMPTY_CART: "emptyCart",
	TEST_ID_EMPTY_CART_IMAGE: "emptyCartImage",
	TEST_ID_CART_ITEM_TITLE: "cartItemTitle",
	TEST_ID_CART_ITEM_QTY: "cartItemQuantity",
	TEST_ID_CART_ITEM_PRICE: "cartItemPrice",

	TEST_ID_ADD_TO_CART_BTN_BOOK1: "TEST_ID_Clean Code",
	TEST_ID_ADD_TO_CART_BTN_BOOK2: "TEST_ID_The Clean Coder",

	TEST_ID_TOTAL_PRICE_LABEL: "TEST_ID_PRICE_TYPE_Total Price",
	TEST_ID_DISCOUNT_PRICE_LABEL: "TEST_ID_PRICE_TYPE_Discount Price",
	TEST_ID_FINAL_PRICE_LABEL: "TEST_ID_PRICE_TYPE_Final Price",

	TEST_ID_TOTAL_PRICE_VALUE: "TEST_ID_PRICE_VALUE_Total Price",
	TEST_ID_DISCOUNT_PRICE_VALUE: "TEST_ID_PRICE_VALUE_Discount Price",
	TEST_ID_FINAL_PRICE_VALUE: "TEST_ID_PRICE_VALUE_Final Price",

	TOTAL_PRICE_FOR_ONE_BOOK: "₹50.00",
	DISCOUNT_PRICE_FOR_ONE_BOOK: "₹0.00",
	FINAL_PRICE_FOR_ONE_BOOK: "₹50.00",
	TOTAL_PRICE_FOR_TWO_BOOK: "₹100.00",
	DISCOUNT_PRICE_FOR_TWO_BOOK: "₹5.00",
	FINAL_PRICE_FOR_TWO_BOOK: "₹95.00",

	BOOK_ONE: 0,

	BOOKS: [
		{
			id: "11d03f1a-66fa-46b1-a473-6a9e24090fb4",
			imgSrc: "./src/assets/Kata_DevelopmentBooks_CleanCode.png",
			title: "Clean Code",
			price: 50,
		},
		{
			id: "d701c4e5-1def-46d7-a3d7-957355fe05fe",
			imgSrc: "./src/assets/Kata_DevelopmentBooks_CleanCoder.png",
			title: "The Clean Coder",
			price: 50,
		},
	],
};
